import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./scss/globals.scss";
import MainLayout from "@/app/components/main-layout/MainLayout";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable}`}>
        <MainLayout />
        {children}
      </body>
    </html>
  );
}
